export const BEAR_LOGO = [
  "            .---.         ",
  "           / o o \\        ",
  "          (   V   )       ",
  "          /|     |\\       ",
  "         / |     | \\      ",
  "        /  |     |  \\     ",
  "     ._/   |     |   \\.   ",
  "    /      _|     |_     \\ ",
  "   | .--''  '---'  ''--. |",
  "   |/    *  ICY   *     \\|",
  "   ;    *  BEAR  *       ;",
  "   |      *     *        |",
  "    \\                   / ",
  "     '._             _.'  ",
  "        '---.___.---'     ",
  "        /    | |    \\     ",
  "       /     | |     \\    ",
  "      '------' '------'   ",
];

export const NEOFETCH_INFO = [
  { label: "", value: "mohit@archlinux", color: "text-terminal-green" },
  { label: "", value: "\u2500".repeat(20), color: "text-terminal-dim" },
  { label: "OS", value: "Arch Linux x86_64" },
  { label: "Host", value: "Portfolio v2.0" },
  { label: "Kernel", value: "6.8.1-arch1" },
  { label: "Shell", value: "mohit-sh 2.0" },
  { label: "Terminal", value: "web-tty" },
  { label: "WM", value: "i3-gaps" },
  { label: "Theme", value: "Nord [GTK3]" },
  { label: "Role", value: "AI Systems Engineer" },
  { label: "Focus", value: "Retrieval Agents / Decision Pipelines" },
  { label: "Location", value: "New Delhi, India" },
  { label: "Uptime", value: "20 years" },
  { label: "Packages", value: "1337 (pacman)" },
  { label: "Memory", value: "4096M / 16384M" },
  { label: "CPU", value: "Neural Engine v2.0 @ 3.6GHz" },
  { label: "GPU", value: "CUDA-accelerated Imagination" },
  { label: "", value: "                              ", color: "text-terminal-dim" },
];
